api/urls.py
from rest_framework.routers import SimpleRouter

from . import views

router = SimpleRouter()

router.register('posts', views.PostViewset, basename='posts')
router.register('subscribers', views.SubscriberViewset, basename='subscribers')

urlpatterns = router.urls

home/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('subscribers.urls')),
    path('news/', include('news.urls')),
    
    # API endpoints
    path('api/', include('api.urls')),
    
    # authentication and authorization
    path('api-auth/', include('rest_framework.urls')),
]

news/urls.py
from django.urls import path

from . import views

app_name = 'news'

urlpatterns = [
    path('', views.newsboard, name='newsboard'),
    path('metrics/', views.metrics, name='metrics'),
    
    # post
    path('post/', views.PostList.as_view(), name='post_list'),
    path('post/create/', views.CreatePost.as_view(), name='create_post'),
    path('post/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    
    # news letter
    path('news-letter/', views.NewsLetterList.as_view(), name='letter_list'),
    path('news-letter/create/', views.CreateLetter.as_view(), name='create_letter'),
    path('news-letter/<int:pk>/', views.NewsLetterDetail.as_view(), name='letter_detail'),
    path('news-letter/previous/', views.PreviousNewsLetterList.as_view(), name='previous_newsletters'),
    path('send_newsletter/<int:pk>/', views.send_newsletter, name='send_newsletter'),
]

news/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'draft'),
        ('published', 'published'),
    )
    
    source = models.URLField(blank=True)
    title = models.CharField(unique=True, max_length=255)
    content = models.TextField()
    image = models.URLField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    validated = models.BooleanField(default=False)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('created_at',)
    
    def __str__(self):
        return self.title


class NewsLetter(models.Model):
    title = models.CharField(max_length=225)
    posts = models.ManyToManyField(Post)
    ready = models.BooleanField(default=False)
    published = models.BooleanField(default=False)
    
    created_at = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(default=timezone.now)
    
    class Meta:
        ordering = ('-created_at',)
    
    def __str__(self):
        return self.title

news/forms.py
from attr import fields
from django import forms

from .models import NewsLetter, Post

class NewsLetterForm(forms.ModelForm):
    class Meta:
        model = NewsLetter
        fields = ('title', 'posts', 'ready')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control w-50'}),
            'posts': forms.CheckboxSelectMultiple(attrs={'class': 'form-control w-50'}),
        }
    posts = forms.ModelMultipleChoiceField(
        queryset=Post.objects.filter(validated=True, status='draft'),
        widget=forms.CheckboxSelectMultiple
    )

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'source', 'image')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control w-50'}),
            'content': forms.Textarea(attrs={'class': 'form-control w-50'}),
            'source': forms.TextInput(attrs={'class': 'form-control w-50'}),
            'image': forms.TextInput(attrs={'class': 'form-control w-50', 'placeholder': 'Image url (optional)'}),
        }

news/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.http import require_POST

from .forms import NewsLetterForm, PostForm
from .models import NewsLetter, Post
from subscribers.models import Subscriber, Unsubscriber
from utility import send_utility


# Post
class CreatePost(LoginRequiredMixin, generic.CreateView):
    form_class = PostForm
    template_name = 'news/create_post.html'
    success_url = reverse_lazy('news:post_list')


class PostList(LoginRequiredMixin, generic.ListView):
    model = Post
    context_object_name = 'posts'


class PostDetail(LoginRequiredMixin, generic.DetailView):
    model = Post
    context_object_name = 'post'


# News Letter
@login_required
def newsboard(request):
    return render(request, 'news/newsboard.html', {})

@login_required
def metrics(request):
    # Subscribers metrics
    subscribers = Subscriber.objects.filter(confirmed=True)
    subs_count =  len(subscribers)
    
    unsubscribers = Unsubscriber.objects.all()
    unsubs_count = len(unsubscribers)
    
    total_user_count = subs_count + unsubs_count
    subscribers_percent =  round((subs_count / total_user_count) * 100, 2)
    unsubscribers_percent = round((unsubs_count / total_user_count) * 100, 2)
    
    # Email metrics
    unread_emails = 0
    read_emails = 0
    for subscriber in subscribers:
        unread_emails += subscriber.delivered_emails
        read_emails += subscriber.opened_emails
        
    read_emails_percent = round((read_emails / unread_emails) * 100, 2)
    unread_emails_percent =  100 - read_emails_percent
    
    context = {
        'subscribers_count': subs_count,
        'subscribers_percent': subscribers_percent,
        'unsubscribers_percent': unsubscribers_percent,
        'unsubscribers_count': unsubs_count,
        'unread_emails': unread_emails,
        'unread_emails_percent': unread_emails_percent,
        'read_emails': read_emails,
        'read_emails_percent': read_emails_percent,
    }
    
    return render(request, 'news/metrics.html', context)


class CreateLetter(LoginRequiredMixin, generic.CreateView):
    form_class = NewsLetterForm
    template_name = 'news/create_letter.html'
    success_url = reverse_lazy('news:letter_list')


class NewsLetterList(LoginRequiredMixin, generic.ListView):
    model = NewsLetter
    context_object_name = 'news'


class PreviousNewsLetterList(generic.ListView):
    model = NewsLetter
    template_name = 'news/previous_newsletters.html'
    context_object_name = 'previous_newsletters'

    def get_queryset(self):
        return super().get_queryset().filter(published=True).order_by('-published_date')


class NewsLetterDetail(generic.DetailView):
    model = NewsLetter
    context_object_name = 'news'


@require_POST
def send_newsletter(request, pk):
    send_utility.send_news_letter(pk)
    return redirect('news:newsboard')

news/templates/news/create_letter.html
{% extends 'index.html' %}

{% block content %}
    <form action="" method="post">
        <h1 class="display-4 my-5">Create letter</h1>
        <h5 class="text-danger">Only validated posts are shown</h5>
        <h5 class="text-danger">Posts are manually validated by Admins</h5>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Add letter!</button>
    </form>
{% endblock %}

news/templates/news/create_post.html
{% extends 'index.html' %}

{% block content %}
    <form action="" method="post">
        <h1 class="display-4 my-5">Create Post</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Add post!</button>
    </form>
{% endblock %}

news/templates/news/metrics.html
{% extends 'index.html' %}

{% block content %}
    <p><i>Subsribers:</i> <b>{{ subscribers_count }}</b></p>
    <p><i>% Subsribers:</i> <b>{{ subscribers_percent }}%</b></p>

    <p><i>Unsubscribers:</i> <b>{{ unsubscribers_count }}</b></p>
    <p><i>% Unsubscribers:</i> <b>{{ unsubscribers_percent }}%</b></p> 
    <br>

    <p><i>Unread mails</i>: <b>{{ unread_emails }}</b></p>
    <p><i>% Unread mails</i>: <b>{{ unread_emails_percent }}%</b></p>

    <p><i>Read mails</i>: <b>{{ read_emails }}</b></p>
    <p><i>% Read mails</i>: <b>{{ read_emails_percent }}%</b></p>
{% endblock%}

news/templates/news/newsboard.html
{% extends 'index.html' %}

{% block content %}
<h1><a href="{% url 'news:post_list' %}">Post list</a></h1>
<h1><a href="{% url 'news:create_post' %}">Create Post</a></h1>
    <br>

    <h1><a href="{% url 'news:letter_list' %}">NewsLetter list</a></h1>
    <h1><a href="{% url 'news:create_letter' %}">Create News Letter</a></h1>
    <h1><a href="{% url 'news:previous_newsletters' %}">Previous News Letter</a></h1>
    <br>

    <h1><a href="{% url 'news:metrics' %}">Metrics</a></h1>
{% endblock %}

news/templates/news/newsletter_detail.html
{% extends 'index.html' %}

{% block content %}
    <h1>{{news.title}}</h1>
    {% for post in news.posts.all %}
        <h4>{{ forloop.counter }}. {{ post.title }}</h4>
        <p>
            {{ post.content }}
        </p>
    {% endfor %}

    {% if news.published == True %}
        <p>Sent, Published!</p>
    {% else %}
        <form action="{% url 'news:send_newsletter' news.id %}" method="post">
            <input type="submit" value="Send newsletter">
            {% csrf_token %}
        </form>
    {% endif %}
{% endblock %}

news/templates/news/newsletter_list.html
{% extends 'index.html' %}

{% block content %}
    {% if news %}

        <h1 class="display-4 my-4">Published Newsletters</h1>
        {% for post in news %}
            {% if post.published %}
                <h2 class="my-5">😊 <a href="{% url 'news:letter_detail' post.id %}">{{ post.title }}</a></h2>
            {% endif %}
        {% endfor %}

        <h1 class="display-4 my-4">Draft Newsletters</h1>
        {% for post in news %}
            {% if post.published == False %}
                <h2 class="my-5">🙁 <a href="{% url 'news:letter_detail' post.id %}">{{ post.title }}</a></h2>
            {% endif %}
        {% endfor %}
    {% else %}
        <p><i>No newsletters yet. <a href="{% url 'news:create_letter' %}">Create News Letter</a></i></p>
    {% endif %}
{% endblock %}

news/templates/news/post_detail.html
{% extends 'index.html' %}

{% block content %}
    <h4>{{ post.title }}</h4>
    <pre>
        {{ post.content }}
    </pre>
{% endblock %}

news/templates/news/post_list.html
{% extends 'index.html' %}

{% block content %}
    {% if posts %}
        {% for post in posts %}
            <h4>{{ forloop.counter }}. <a href="{% url 'news:post_detail' post.id %}">{{ post.title }}</a></h4>
        {% endfor %}
    {% else %}
        <p><i>No posts yet. <a href="{% url 'news:create_post' %}">Create Post</a></i></p>
    {% endif %}
{% endblock %}

news/templates/news/previous_newsletters.html
<div class="my-5">
    <h1>Previous Newsletters</h1>

    {% if previous_newsletters %}
        <div>
            {% for post in previous_newsletters %}
                <div class="row py-2 text-align-center">
                    <h4 class="col-6">{{ forloop.counter }}. <a href="{% url 'news:letter_detail' post.id %}"><i>{{ post.title }}</i></a></h4>
                    <p class="col-6">
                        <span class="text-end">{{ post.published_date.date }}</span>
                    </p>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p><i>Newsletters haven't been sent</i></p>
    {% endif %}
</div>