api/urls.py
from rest_framework.routers import SimpleRouter

from . import views

router = SimpleRouter()

router.register('posts', views.PostViewset, basename='posts')
router.register('subscribers', views.SubscriberViewset, basename='subscribers')

urlpatterns = router.urls

home/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('subscribers.urls')),
    path('news/', include('news.urls')),
    
    # API endpoints
    path('api/', include('api.urls')),
    
    # authentication and authorization
    path('api-auth/', include('rest_framework.urls')),
]

subscribers/urls.py
from django.urls import path

from . import views

app_name = 'subscribers'

urlpatterns = [
    path('', views.add_subscriber, name='add'),
    path('confirm/<uidb64>/<token>/', views.confirm_subscriber, name='confirm'),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),
    path('image_load/<uidb64>/<token>/', views.image_load, name='image_load'),
]

subscribers/models.py
from django.db import models


class Subscriber(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(blank=True, max_length=25)
    email = models.EmailField(unique=True)

    confirmed = models.BooleanField(default=False)  # True if subscriber confirms email
    
    delivered_emails = models.IntegerField(default=0)
    opened_emails = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


class Unsubscriber(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(blank=True, max_length=25)
    email = models.EmailField(unique=True)
    
    delivered_emails = models.IntegerField(default=0)
    opened_emails = models.IntegerField(default=0)
    
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

subscribers/forms.py
from django import forms

from .models import Subscriber, Unsubscriber

my_default_errors = {
    'unique': 'You are not a subscriber',
    'invalid': 'Enter a valid email address',
}

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ('first_name', 'last_name', 'email')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control w-50'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control w-50'}),
            'email': forms.TextInput(attrs={'class': 'form-control w-50'}),
        }

class UnsubscribeForm(forms.ModelForm):
    class Meta:
        model = Unsubscriber
        fields = ('email',)
        
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control w-50',}),
        }
        error_messages = {
            'email': my_default_errors,
        }
        
    def clean(self):
        email = self.cleaned_data.get('email')
        try:
            sub_email = Subscriber.objects.get(email=email)
        except Subscriber.DoesNotExist:
            raise forms.ValidationError('You are not a subscriber')
        return super().clean()

subscribers/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.html import strip_tags
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from PIL import Image

from .forms import SubscribeForm, UnsubscribeForm
from .models import Subscriber
from .tokens import account_activation_token
from news.models import NewsLetter
from utility.send_utility import send_confirmation_mail


def add_subscriber(request):
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            subscriber = form.save(commit=False)
            form.save()
            
            # Send Confirmation Email
            email_context = {
                'subscriber': subscriber,
                'action': 'added',
                'domain': get_current_site(request).domain,
                'uid': urlsafe_base64_encode(force_bytes(subscriber.pk)),
                'token': account_activation_token.make_token(subscriber),
                'protocol': 'https' if request.is_secure() else 'http',
            }
            html_content = render_to_string('emails/confirm_subscription.html', email_context)
            plain_text_content = strip_tags(html_content)
            send_confirmation_mail(subscriber.email, plain_text_content, html_content)
            
            context = {
                'subscriber': subscriber,
            }
            return render(request, 'subscribers/subscription_complete.html', context)
    else:
        form = SubscribeForm()
    previous_newsletters = NewsLetter.objects.filter(published=True).order_by('-published_date')
    
    context = {
        'form': form,
        'previous_newsletters': previous_newsletters,
    }
    return render(request, 'subscribers/add_subscriber.html', context)


def confirm_subscriber(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        subscriber = Subscriber.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Subscriber.DoesNotExist):
        subscriber = None

    if subscriber is not None and account_activation_token.check_token(subscriber, token):
        subscriber.confirmed = True
        subscriber.save()
    else:
        return HttpResponse('Something went wrong, please try again')

    return render(request, 'subscribers/subscription_complete.html', {'subscriber': subscriber})


def unsubscribe(request):
    if request.method == 'POST':
        form = UnsubscribeForm(request.POST)
        if form.is_valid():
            unsubcriber = form.save(commit=False)
            subscriber = Subscriber.objects.get(email=unsubcriber.email)
            unsubcriber.first_name = subscriber.first_name
            unsubcriber.last_name = subscriber.last_name
            unsubcriber.delivered_emails = subscriber.delivered_emails
            unsubcriber.opened_emails = subscriber.opened_emails
            unsubcriber.save()
            subscriber.delete()
            
            context = {'unsubcriber': unsubcriber}
            return render(request, 'subscribers/unsubscribe_complete.html', context)
    else:
        form = UnsubscribeForm()

    context = {'form': form}

    return render(request, 'subscribers/unsubscribe.html', context)


# For tracking if user opens email
def image_load(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        subscriber = Subscriber.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Subscriber.DoesNotExist):
        subscriber = None

    if subscriber is not None and account_activation_token.check_token(subscriber, token):
        subscriber.opened_emails += 1
        subscriber.save()
        red = Image.new('RGB', (1, 1))
        response = HttpResponse(content_type='image/png')
        red.save(response, 'PNG')
        return response
    else:
        return HttpResponse('Something went wrong')

subscribers/templates/subscribers/add_subscriber.html
{% extends 'index.html' %}
{% block content %}
    <div class="d-flex justify-content-center">
        <form class="col-lg-12 col-md-6 col-sm-12 my-5" method="post">
            {% csrf_token %}
            <h1 class="display-4 mb-5">The Humore</h1>
            <div>
                {{form.as_p}}
            </div>
            <button class="btn btn-success" type="submit">Subscribe!</button>
        </form>
    </div>

    <!-- previous newsletters list -->
    {% include 'news/previous_newsletters.html' %}
{% endblock %}

subscribers/templates/subscribers/subscription_complete.html
{% extends 'index.html' %}

{% block content %}
    <p>Thanks a bunch {{ subscriber.first_name }} 🥹</p>
    <p>You just made our little family grow a little bigger</p>
    <a href=""><button>See previous emails sent</button></a>
{% endblock %}

subscribers/templates/subscribers/subscription_confirm.html
{% extends 'index.html' %}

{% block title %} complete subscription {% endblock %}

{% block content %}
    <h1 class="display-4 mb-5">Thanks! we'll add you to the newsletter</h1>
    <p>
        A link has been sent to your email to confirm your subscription
    </p>

    <h3 class="display-5 my-3">What to expect from the newsletter</h3>
    <p>
        We send out letters  everyweek throught email
        about *subject*
    </p>

    <h3 class="display-5 my-3">Get helpful reminders</h3>
    <p>
        If you would find it helpful to receive reminders for our newsletters... then follow us on Twitter
    </p>
    <span> <a href="">Follow us on twitter</a></span>
{% endblock %}

subscribers/templates/subscribers/unsubscribe.html
{% extends 'index.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1 class="display-4 my-5 w-50">Unsubscribe from our list</h1>
        {{ form.as_p}}
        <button class="btn btn-success" type="submit">Unsubscribe!</button>
    </form>
{% endblock %}

subscribers/templates/subscribers/unsubscribe_complete.html
{% extends 'index.html' %}

{% block content %}
    leaving so soon {{ unsubcriber.first_name }} 🙁?
    <p><a href="{% url 'subscribers:add' %}">Click this link to be added back to our list</a></p>
{% endblock %}